# Grafana Datasource Configuration - Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    version: 1

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://valkey:6379
    jsonData:
      tlsAuth: false
      tlsSkipVerify: false
    version: 1

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: erp
    user: postgres
    password: postgres
    jsonData:
      sslmode: disable
      version: 16
    version: 1
